id: PA6406F84
initial_creation_type: input
source_metadata:
  title: Sickness and Healing
  language: es
  description: 'Lotsawa House presents the following texts as part of our Sickness
    and Healing Series:'
  volume:
    52818a2de2254359bcdd7f1a23f79b75:
      title: Three Ways of Bringing Sickness onto the Path
      parent: Advice
    5b7275eb5f6047d39c6aae767b333381:
      title: How to Transform Sickness and Other Circumstances
      parent: Advice
    b2d9c6574af34d0087f87016b3c8f9b9:
      title: The Universal Medicine for Healing All Ills
      parent: Advice
    1cc049133f394f3a95827f97cabf848a:
      title: The Mantra Collection that Incinerates All the Diseases of this Kaliyuga
      parent: Mantras
    56be3cf1a71c4272b46ab2e56e0fd694:
      title: Wrathful Guru Mantra Visualization
      parent: Mantras
    c05c7c0fbf19463da4341334e9172f03:
      title: Dhāraṇī of Goddess Parṇaśavarī
      parent: Practices
    14be2599e7744de49a922ac0aecd068b:
      title: Daily Practice of Guru Rinpoche, Buddha of Medicine
      parent: Practices
    a9caaea66f394f81ad7a46874cf65a8b:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Practices
    3d5e3026e5f1420d818ee946b02e219d:
      title: Daily Practice of Dorje Gotrab
      parent: Practices
    43d4cce8c9004978923f55eb51faf264:
      title: 'Fast Track to Happiness and Peace: A Very Brief Meditation and Recitation
        of the Medicine Buddha'
      parent: Practices
    3d077fd09c1546849a032593b66c6d91:
      title: Sādhana of Bhaiṣajya Guru (Medicine Buddha)
      parent: Practices
    3918bf1282744ae8bf6ca93d432571c0:
      title: 'Zabchema: Profound Cure, The Practice of Bhaiṣajya-Guru, Lord of Physicians'
      parent: Practices
    d9e6901f7c14464b9f61ef8018abc5c7:
      title: Acala Sādhana
      parent: Practices
    86eb968c68254dec82ee07f7145af344:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Practices
    a9587e8eea0b46a592ad6f3d00639b65:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Prayers
created_at: '2022-03-01T05:47:13.660209'
last_modified_at: '2022-03-01T05:47:13.660212'
